# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:46
from __future__ import unicode_literals

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    """
    Para cada ABC, instanciar um MTI com todos os atributos
    salvar MTI
    associar os speakers do adc no mti
    deletar o abc

    :param apps:
    :param schema_editor:
    :return:
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    """
    O inverso da funçao forward_course_abc_to_mti
    :param apps:
    :param schema_editor:
    :return:
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
